akhavr/electrum-dash

RELEASE-NOTES
contrib/sign-releases.py
lib/version.py

* add sign apk code to `contrib/sign-releases.py`
* remove unused `check_github_repo`
* change version to 3.0.6.1, add RELEASE-NOTES

Add sign apk code

---

README.rst

* Add note on install x11-hash to packages

fix README.rst (note on install x11-hash to packages)

---

RELEASE-NOTES
gui/qt/dash_style.py
lib/version.py
plugins/ledger/ledger.py

* fix ledger plugin to python3
* fix QComboBox css
* version to 3.0.6.2

fix ledger/qt css/version to 3.0.6.2

---

RELEASE-NOTES
lib/base_wizard.py
lib/version.py

Fix bip44_derivation call

---

RELEASE-NOTES
gui/qt/amountedit.py
lib/version.py

* enlarge amount field witdh on 25%

enlarge amount field witdh

---

RELEASE-NOTES
gui/qt/dash_style.py

* Fix сss of InvoiceList, RequestList, Send From (coins)

fix send/receive tabs QTreeView CSS

---

RELEASE-NOTES
contrib/dash/deterministic.spec
contrib/dash/travis/Dockerfile-wine
contrib/dash/travis/build_wine.sh
contrib/dash/travis/travis-build-linux.sh
lib/blockchain.py
lib/qrscanner.py
plugins/digitalbitbox/digitalbitbox.py
setup.py

- Use new zbarw binaries built with 64-bit support (from https://github.com/zebra-lucky/zbarw/releases),
change build scripts
- Fix `scan_barcode` call (slow zbarw load)
- Fix setup.py (change icon, data files)
- Add relnotes about checkpoints
- Fix mistakenly entered blockchain constant name

Fix QR scan, other fixes

---

lib/ecc_fast.py

fix ecc_fast.py for win64

---

README.rst
docs/tor.md

- describe PPA setup in README.rst
- describe Tor Proxy setup in README.rst
- fix version when tor_auto_on added (3.2.3.1)

Fix README.rst

---

electrum_dash/dash_tx.py
electrum_dash/gui/qt/masternode_budget_widgets.py
electrum_dash/tests/test_dash_tx.py
electrum_dash/tests/test_transaction.py
electrum_dash/transaction.py

- add DIP2 aware deserialization/serialization (Ref URLs: https://github.com/dashpay/dips/blob/master/dip-0002.md
https://github.com/dashpay/dips/blob/master/dip-0002-special-transactions.md)
- small fix to gettext call to run xgettext without warning

Add dip2 aware deserializer

---

contrib/update-latest-version.py
electrum_dash/gui/qt/update_checker.py

- Add contrib/update-latest-version.py script
- Fix update checker urls

Add update latest version script

---

RELEASE-NOTES
electrum_dash/gui/qt/protx_qt.py
electrum_dash/gui/qt/protx_wizards.py

- allow offline operation
- fix display of loading state
- update diff data/display when disconnected/reconnected

protx: update UI logic on protx tab, export import protx tab data

---

electrum_dash/gui/qt/protx_wizards.py

A few minor typos/wording updates

DIP3 Screen typo fixes

---

electrum_dash/gui/qt/protx_wizards.py

Correct advised dash.conf filename

---

contrib/dash/exsrvmonit/Makefile
contrib/dash/exsrvmonit/exsrvmonit.py
contrib/dash/exsrvmonit/exsrvmonit.spec

- exsrvmonit.py to run from cron
- spec and Makefile to build binary to run without requirements (to simplify cron run)

add contrib exsrvmonit.py script to monitor active electrumx servers

---

electrum_dash/gui/kivy/uix/dialogs/installwizard.py
electrum_dash/gui/qt/main_window.py
electrum_dash/gui/qt/masternode_budget_widgets.py
electrum_dash/gui/qt/masternode_dialog.py
electrum_dash/gui/qt/update_checker.py
electrum_dash/masternode_manager.py

- fixes for #87, #88, #89
- disable rich_text in gui/qt/masternode* (using utils methods to show MsgBoxes)
- fix gui/qt/update_checker.py to not fail on 3.3.8rc1

Fixes 87 88 89

---

RELEASE-NOTES
electrum_dash/dash_tx.py
electrum_dash/gui/qt/console.py
electrum_dash/gui/qt/dark_dash_style.py
electrum_dash/gui/qt/dash_style.py
electrum_dash/gui/qt/main_window.py
electrum_dash/version.py

- fix wallet locking during verification of DIP3 transactions
- add qt console password locking for SW wallets

Add qt console password locking

---

contrib/update-latest-version.py
docs/os-specific.md

- Add docs on os specific
- fix update-latest-version.py to write new line at enf of latest version file

Add docs on os specific

---

electrum_dash/dash_ps.py
electrum_dash/tests/test_dash_ps.py

- fix _cleanup_spendable_keypairs, add test_cleanup_spendable_keypairs
- optimize _find_addrs_not_in_keypairs, add test
- fix excess trailing spaces in strings

Fix _cleanup_spendable_keypairs

---

electrum_dash/gui/kivy/main_window.py

- add run orbot/redetect tor buttons if tor not detected on startup

kivy: allow run orbot on wallet start and redetect tor proxy

---

RELEASE-NOTES
electrum_dash/dash_ps.py
electrum_dash/tests/test_dash_ps.py

- allow start mixing before llmq/protx ready
- stop mixing only if keep amount is available on ps balance
- add test_all_mixed

PS: enhance start stop mixing

---

RELEASE-NOTES
electrum-dash
electrum_dash/commands.py
electrum_dash/gui/kivy/main_window.py
electrum_dash/gui/kivy/uix/dialogs/dash_kivy.py
electrum_dash/gui/kivy/uix/ui_screens/network.kv
electrum_dash/gui/qt/__init__.py
electrum_dash/gui/qt/dark_dash_style.py
electrum_dash/gui/qt/dash_qt.py
electrum_dash/gui/qt/dash_style.py
electrum_dash/gui/qt/main_window.py
electrum_dash/gui/qt/network_dialog.py
electrum_dash/gui/stdio.py
electrum_dash/gui/text.py
electrum_dash/network.py

- fix relnotes for 3.3.8.5
- commmands.py: add --no-proxy option
- fix qt disabled widgets CSS
- tor_auto_on: modify behaviour/UI
- fix kivy app exit if mixing is run (check app has wallet loaded and exit with stopTouchApp)

Enhance tor_auto_on behaviour/UI

---

RELEASE-NOTES
electrum_dash/address_synchronizer.py
electrum_dash/dash_ps.py
electrum_dash/gui/kivy/main_window.py
electrum_dash/gui/kivy/uix/dialogs/coins_dialog.py
electrum_dash/gui/qt/main_window.py
electrum_dash/gui/qt/utxo_list.py

- enhance UI to handle PS Other coins
- fix wallet.get_utxos related to other coins
- fix add/rm new denoms/collateral ps data related to other coins

Add more UI to handle PS Other coins

---

RELEASE-NOTES
electrum_dash/commands.py
electrum_dash/gui/qt/history_list.py
electrum_dash/gui/qt/main_window.py
electrum_dash/gui/qt/protx_wizards.py
electrum_dash/gui/qt/util.py
electrum_dash/util.py

- qt: fix eported files mode
- commands: fix broadcast command

Fix exported files file mode, fix broadcast command

---

contrib/requirements/requirements.txt
electrum_dash/gui/qt/main_window.py

- add do not show again checkbox to watching only warning
- preferences general (allow enable warning again)

qt: add do not show again checkbox to watching only warning

---

electrum_dash/gui/kivy/main_window.py
electrum_dash/gui/qt/main_window.py
electrum_dash/gui/qt/paytoedit.py
electrum_dash/tests/test_util.py
electrum_dash/util.py

- allow "pay" payment scheme if "r" query param used, check it in tests

Add pay to pay schemes

---

electrum_dash/dash_ps.py
electrum_dash/gui/qt/history_list.py

- qt: fix history_list menu if column data is None
- fix typo

Qt fix history list menu if column data is None

---

electrum_dash/gui/qt/console.py

- Clean console.py (https://github.com/spesmilo/electrum/pull/6384)
- Remove empty startup message from console (https://github.com/spesmilo/electrum/pull/6467)

qt console: fixes from upstream

---

RELEASE-NOTES
electrum_dash/dash_net.py
electrum_dash/dash_peer.py
electrum_dash/network.py
electrum_dash/protx_list.py

- process timeout on awaiting data msg from peer
- add 'network-error' notification to MNList to repeat data loading

Protx fix network data processing

---

electrum_dash/protx_list.py

- protx_list: fix divizion by zerro

protx_list: fix divizion by zerro

---

electrum_dash/dash_ps.py

- do not cache incoming addresses on hw wallets
- add try/except block in _make_keypairs_cache

Ps fix keypairs calc on small funds on hw wallets

---

electrum_dash/gui/qt/main_window.py

- fix main window close event (do not stop get data threads to early)

qt: fix main windown close event

---

RELEASE-NOTES
electrum_dash/gui/kivy/main_window.py
electrum_dash/gui/kivy/uix/dialogs/dash_kivy.py

- fix TorWarnDialog.on_ok signature
- run_other_app: run new task in separate thread (seems fixes SIGSEGV in SDLThread)
- add text to RELEASE-NOTES

Kivy fix TorWarnDialog

---

electrum_dash/gui/qt/history_list.py
electrum_dash/gui/qt/main_window.py
electrum_dash/gui/qt/protx_qt.py
electrum_dash/gui/qt/protx_wizards.py
electrum_dash/protx.py
electrum_dash/wallet.py

- fixses related to tx_type/extra_payload, dip3 MNs
- temporarily comment out `maybe_defer_update` as does not always update when needed
- fix logic in on_wallet_selection_changed

Post 4x fixes to dip3/protx code

---

contrib/update-latest-version.py

- contrib/update-latest-version.py: adapt to 4.x wallet code
- replace missed `print_msg` to `print`

contrib/update-latest-version.py: adapt to 4.x wallet code

---

electrum_dash/gui/qt/main_window.py

- qt: rm max amount fixed width

qt fix: remove max amount button fixed width

---

electrum-dash
electrum_dash/commands.py
electrum_dash/stacktraces.py

- extend stacktraces use for mainnet

extend stacktraces use for mainnet

---

electrum_dash/gui/qt/protx_qt.py

- qt: fix dip3 tab in offline mode

qt: fix dip3 tab in offline mode

---

electrum_dash/transaction.py

- fix Transaction.input_script for size estimation (must fix #161)

Fix Transaction.input_script for size estimation

---

electrum_dash/gui/kivy/data/style.kv
electrum_dash/gui/kivy/main.kv

- kivy: move PSActionButton from data/style.kv to main.kv (fix android app crash)

kivy: move PSActionButton from data/style.kv to main.kv

---

electrum_dash/wallet.py

- wallet: fix _is_onchain_invoice_paid to prevent deadlocks

wallet: fix _is_onchain_invoice_paid to prevent deadlocks

---

RELEASE-NOTES
electrum_dash/version.py

- version to 4.0.9.1, add RELEASE-NOTES

version to 4.0.9.1, add RELEASE-NOTES

---

electrum-dash

- android: fix config for run_stacktaces check

android: fix config for run_stacktaces check

---

electrum_dash/gui/qt/paytoedit.py

- qt: fix PayToEdit.parse_amount

qt: fix PayToEdit.parse_amount

---

electrum_dash/gui/kivy/uix/dialogs/dash_net.py
electrum_dash/gui/qt/protx_qt.py
electrum_dash/protx_list.py

- gui qt/kivy: add ProTx/LLMQ reset UI

gui qt/kivy: add ProTx/LLMQ reset UI

---

electrum_dash/gui/qt/privatesend_dialog.py

- qt PS dialog: fix PS Keystore tab

qt PS Dialog: fix PS Keystore tab

---

electrum_dash/util.py

- util.py: fix mainnet Dash.org block explorer (related to #178)

util.py: fix mainnet Dash.org block explorer

---

RELEASE-NOTES
electrum_dash/dash_tx.py
electrum_dash/gui/kivy/uix/dialogs/invoice_dialog.py
electrum_dash/gui/kivy/uix/screens.py
electrum_dash/gui/qt/invoice_list.py
electrum_dash/gui/qt/main_window.py
electrum_dash/invoices.py
electrum_dash/tests/test_dash_tx.py
electrum_dash/wallet.py
electrum_dash/wallet_db.py

* invoices: add InvoiceExt with Dash extra data support,
which includes PrivateSend send status and DIP2 extra data/tx type

invoices: add InvoiceExt with Dash extra data support

---

contrib/sign-releases.py

Allow only make PPA on launchpad.net with `-P`/`--only-ppa` option,
if previous run failed after successful release sign.
#200 related

contrib/sign-releases.py: add -P/--only-ppa option

---

electrum_dash/gui/kivy/uix/screens.py

- kivy: fix history screen tx_type processing

kivy: fix history screen tx_type processing

---

electrum_dash/gui/qt/main_window.py

Pass `InvoiceExt` data to `do_pay_invoice` to send tx
with extra_payload when invoice is not saved yet. (#208 related)

qt: pass InvoiceExt data to do_pay_invoice

---

electrum-dash
electrum_dash/daemon.py

- fix run_offline_command: do backup old version
- fix backup msg output for daemon/offline commands

Fix offline command backup old version on wallet upgrade

---

electrum_dash/gui/kivy/main.kv
electrum_dash/gui/kivy/main_window.py
electrum_dash/gui/kivy/uix/dialogs/plugins.py
electrum_dash/gui/kivy/uix/dialogs/settings.py
electrum_dash/gui/qt/dark_dash_style.py
electrum_dash/gui/qt/dash_style.py
electrum_dash/gui/qt/main_window.py
electrum_dash/plugins/scan_over_gap/__init__.py
electrum_dash/plugins/scan_over_gap/kivy.py
electrum_dash/plugins/scan_over_gap/qt.py
electrum_dash/plugins/scan_over_gap/scan_over_gap.py

- Add plugin to scan wallet for lost coins on addresses beyond gap limits.
additionaly:
- Fix qt code (CSS, plugins dialog)
- Fix kivy code (add `PluginsDialog`, fix `SettingsDialog`)
Screens:
<image src="https://user-images.githubusercontent.com/992125/111585827-93ee2980-87c8-11eb-83a7-350a35bd549e.png" width="400">
<image src="https://user-images.githubusercontent.com/992125/111585831-9486c000-87c8-11eb-9367-955c943c6a09.png" width="300"> <image src="https://user-images.githubusercontent.com/992125/111585832-951f5680-87c8-11eb-82b7-6948b9993d06.png" width="300">

Add plugin scan_over_gap

---

electrum_dash/address_synchronizer.py
electrum_dash/gui/qt/settings_dialog.py
electrum_dash/gui/qt/utxo_list.py
electrum_dash/transaction.py

- qt: add show_utxo_time config/qt option (Fix #218)
Screen:
<image src="https://user-images.githubusercontent.com/992125/111672923-1b688680-8823-11eb-8dcd-f741471b4cff.png" width="500">

qt: add show_utxo_time config/qt option

---

electrum_dash/dash_msg.py
electrum_dash/dash_ps_util.py
electrum_dash/dash_ps_wallet.py
electrum_dash/gui/kivy/uix/dialogs/privatesend.py
electrum_dash/gui/qt/privatesend_dialog.py
electrum_dash/tests/test_dash_ps.py
electrum_dash/util.py

Allow mix determined count of denoms. Possibly fix #203
Some screens:
<image src="https://user-images.githubusercontent.com/992125/112853946-06f37c00-90b6-11eb-9f90-e9fe10e15adb.png" width="500">
<image src="https://user-images.githubusercontent.com/992125/112853963-0bb83000-90b6-11eb-8bc3-5e887ed88508.png" width="500">
<image src="https://user-images.githubusercontent.com/992125/112853984-11ae1100-90b6-11eb-8343-2291c6cf9d9d.png" width="300">
<image src="https://user-images.githubusercontent.com/992125/112853990-14106b00-90b6-11eb-8090-86c9dbbd5a63.png" width="300">

dash_ps: allow set absolute denoms count to mix

---

RELEASE-NOTES
contrib/dash/actions/script-linux-apk.sh
contrib/dash/travis/travis-build-linux-apk.sh
contrib/sign-releases.py
electrum_dash/dash_ps_wallet.py
electrum_dash/gui/qt/confirm_tx_dialog.py
electrum_dash/version.py

- qt: fix ps keystore password check
- dash_ps: fix _prepare_funds_from_hw_wallet
- contrib: rm staled code from apk build scripts
- add 21.04 to sign_releases.py (ubuntu 21.04)
- version to 4.0.9.4, add RELEASE-NOTES

fixes for privatesend with hw wallet

---

electrum_dash/commands.py

- commands history: remove stalled config kwarg
Fixes #228

commands history: remove stalled config kwarg

---

electrum_dash/base_wizard.py
electrum_dash/keystore.py

Аdd purpose48 multisig as default multisig method
Fix #235

base_wizard.py, keystore.py: add purpose48 multisig

---

electrum_dash/dash_ps.py
electrum_dash/dash_ps_util.py
electrum_dash/dash_ps_wallet.py
electrum_dash/wallet_db.py

Fix #241
additional code is for support of wallets before ps keystore added
or for imported core wallets

dash_ps: enhance new denoms/collateral patterns

---

electrum_dash/dash_ps_wallet.py
electrum_dash/tests/test_dash_ps.py

- dash_ps: fix _calc_total_need_val
Fix #236

dash_ps: fix _calc_total_need_val

---

electrum_dash/gui/qt/main_window.py
electrum_dash/gui/qt/protx_qt.py
electrum_dash/gui/qt/protx_wizards.py

- qt dip3: make wizards modeless
#Fix #230

qt dip3: make wizards modeless

---

electrum_dash/base_wizard.py

- base_wizard.py: fix choose_keystore (create seed)

base_wizard.py: fix choose_keystore (create seed)

---

electrum_dash/gui/kivy/main.kv
electrum_dash/gui/kivy/main_window.py
electrum_dash/gui/qt/main_window.py
electrum_dash/interface.py
electrum_dash/network.py
electrum_dash/protx_list.py

* kivy: add network data loading progress bar on top of app
* notify when server disconnected on excessive resource usage (limits)
* protx_list: load ProTx diffs after blockchain/wallet updated
Related to #191

kivy: net data loading progress bar, notify server limits, delay ProTx loading

---

contrib/build-linux/sdist/build.sh
contrib/build-wine/Dockerfile
contrib/build-wine/build.sh
contrib/build-wine/deterministic.spec
contrib/dash/actions/install-linux.sh
contrib/dash/actions/install-osx.sh
contrib/dash/actions/script-linux.sh
contrib/dash/actions/script-osx.sh
contrib/dash/build.sh
contrib/dash/pyi_runtimehook.py
contrib/dash/travis/before_install-linux.sh
contrib/dash/travis/before_install-osx.sh
contrib/dash/travis/travis-build-linux.sh
contrib/dash/travis/travis-build-osx.sh
contrib/osx/osx.spec
contrib/osx/osx_actions.spec
electrum_dash/servers.json
electrum_dash/stacktraces.py

- Win/macOS build: renew packages, build fixes
- fix PyInstaller build for scan_over_gap plugin
- fix stacktraces run on Win platforms
- servers.json: rm electrum.dash.siampm.com (NXDOMAIN)

Renew build dependencies for macOS/Win, other fixes

---

electrum_dash/network.py

- network: do not stop dash_net/mn_list if not full_shutdown

network: do not stop dash_net/mn_list if not full_shutdown

---

electrum_dash/dash_ps.py
electrum_dash/dash_ps_net.py
electrum_dash/dash_ps_util.py
electrum_dash/dash_ps_wallet.py
electrum_dash/tests/test_dash_ps.py

- dash_ps: fix processing of new_denoms/collateral wfls

PS: fix processing of new_denoms/collateral wfls

---

electrum_dash/dash_ps_wallet.py

- dash_ps: do not check enough small denoms for ABS calc method

PS: do not check enough small denoms for ABS calc method

---

electrum_dash/dash_ps.py
electrum_dash/dash_ps_net.py
electrum_dash/dash_ps_util.py
electrum_dash/dash_ps_wallet.py
electrum_dash/gui/kivy/uix/dialogs/privatesend.py
electrum_dash/gui/qt/privatesend_dialog.py
electrum_dash/tests/test_dash_ps.py

- dash_ps/qt/kivy: add gather_mix_stat option
- dash_ps_util.py: add DSMsgStat, MixingStats util classes
- dash_ps: gather stat info and show in info tab
- add test_MixingStats_DSMsgStat, test_gather_mix_stat
Fixes #264

PS: add gathering mixing statistics

---

electrum_dash/gui/qt/protx_wizards.py
electrum_dash/protx.py

- protx/qt: allow add MN with IP/BLS pubk found in registered MNs
Fix #250

protx/qt: allow add MN with IP/BLS pubk found in registered MNs

---

electrum_dash/protx_list.py

- protx_list: MNList.reset: notify gui, clear protx_info data
- protx_list: add more debug logging

protx_list: MNList.reset: notify gui, clear protx_info data

---

RELEASE-NOTES
contrib/build-wine/Dockerfile
contrib/build-wine/build.sh
contrib/build-wine/build_pyinstaller.sh
contrib/build-wine/build_secp256k1.sh
contrib/build-wine/build_x11_hash.sh
contrib/dash/actions/script-linux.sh
contrib/dash/travis/travis-build-linux.sh
electrum_dash/version.py

- build-wine: release rebuild of PyInstaller/secp256k1/x11-hash
- version to 4.1.2.2, add RELEASE-NOTES

Prepare 4.1.2.2 release

---

electrum_dash/currencies.json
electrum_dash/exchange_rate.py

- exchange_rate.py: rm exchanges with OTS public API
- currencies.json: add CHF currency to CoinGecko
- exchange_rate.py: add Kraken (USD, EUR, BTC)
Fix #276
Fix #277

exchange_rate: add CHF to CoinGecko, add Kraken

---

electrum_dash/servers.json
electrum_dash/servers_testnet.json

- change tor servers dns to v3

change tor servers dns to v3

---

electrum_dash/address_synchronizer.py

- address_synchronizer: add _tx_deltas_related_txs (fix #282)

address_synchronizer: add _tx_deltas_related_txs (fix #282)

---

electrum_dash/gui/kivy/main_window.py

- kivy: make the PS shield button simply start mixing

Kivy: make the PS shield button simply start mixing

---

electrum_dash/coinchooser.py
electrum_dash/dash_ps_util.py
electrum_dash/gui/kivy/uix/dialogs/confirm_tx_dialog.py
electrum_dash/gui/kivy/uix/dialogs/privatesend.py
electrum_dash/gui/qt/main_window.py
electrum_dash/gui/qt/privatesend_dialog.py
electrum_dash/tests/test_dash_ps.py
electrum_dash/wallet.py

- optionally allow ps coinchooser to spend high fees
related to #300, #303, #305

PrivateSend: optionally allow ps coinchooser to spend high fees

---

electrum_dash/gui/kivy/main.kv
electrum_dash/gui/kivy/main_window.py

- fix for #310 PS shield button simply start mixing

fix for #310 PS shield button simply start mixing

---

electrum_dash/gui/kivy/main_window.py
electrum_dash/gui/kivy/uix/dialogs/password_dialog.py

- kivy: allow switch to digits only password dialog

Kivy: allow switch to digits only password dialog

---

electrum_dash/gui/kivy/uix/dialogs/dash_net.py

- kivy: unite Dash network static peers setttings
Leave only one item for static peers in Dash network settings.
Place "Use Static Peers" checkbox in `the StaticPeersPopup`
Fix #307

Kivy: unite Dash network static peers setttings

---

electrum_dash/gui/kivy/main_window.py
electrum_dash/gui/qt/__init__.py
electrum_dash/gui/qt/main_window.py

Info about Ukraine support

---

electrum_dash/gui/kivy/uix/dialogs/dash_kivy.py

kivy: fix PR #323 changes

---

contrib/build-linux/ppa/Dockerfile
contrib/build-linux/ppa/build_docker_image.sh
contrib/build-linux/ppa/build_ppa.sh
contrib/sign-releases.py

- sign_releases: build PPA in docker container
Fix #332

sign_releases: build PPA in docker container

---

electrum_dash/network.py

- network: remove tx-txlock-conflict from blacklist errors
related to #323

network: remove tx-txlock-conflict from blacklist errors

---

RELEASE-NOTES
electrum_dash/version.py

- version to 4.1.5.2, add RELEASE-NOTES

version to 4.1.5.2, add RELEASE-NOTES
