contrib/sign-releases.py

- Use `./contrib/sign-releases.py -S p1` will make ppa `version+p1`

add --ppa-upstream-suffix opt to sign-releases.py

---

RELEASE-NOTES
contrib/dash/travis/Dockerfile-wine
lib/version.py

- change Dockerfile to install vcrun2015 x64 manually instead using winetricks (docker image on hub.docker.com is already rebuilded)
- version to 3.2.2.1, add relnotes

Fix win64 vcrun2015 builds

---

plugins/trezor/trezor.py

https://github.com/akhavr/electrum-dash/issues/44
In old trezor-common code there was no coin definition
for Dash testnet, so previous name was get without space.

fix trezor Dash coin name for testnet

---

.travis.yml
contrib/sign-releases.py
electrum_dash/gui/kivy/tools/buildozer.spec

- Back to `Electrum_DASH` package name
- rename to `Dash-Electrum` during release signing process
- additional improvement for release signing: set release name/body (description) when making ppa

Fix rename app in PR #51

---

electrum_dash/masternode_manager.py

Fix to issue #58
Subscribe to all masternodes if some collateral set.

quick fix subscription to masternodes

---

electrum_dash/gui/qt/main_window.py
electrum_dash/util.py

When copying text of message to sign from rich text editors, there is rich formating copied together with text and confusions possible during verify process. This patch disables acceptRichText on QTextEdit field for message.

fix sign/encrypt msg fields not to accept rich text

---

electrum_dash/gui/kivy/uix/screens.py

kivy receive screen: copy address to clipboard if amount is not set, set qr data as address if amount is not set

kivy receive screen: copy/set QR code to address if amount is not set

---

contrib/sign-releases.py
electrum_dash/address_synchronizer.py
electrum_dash/dash_ps.py
electrum_dash/tests/test_dash_ps.py

- Fix get_balance bug when min_rounds >= 0 and ps_other with same address as ps_denom exists
- rm excess get_balance call from psman.mixing_progress
- rm disco build from contrib/sign-releases.py (End of Life on January 23, 2020)

Fix get balance for ps balance when ps_others exists

---

electrum_dash/dash_ps.py
electrum_dash/gui/kivy/main_window.py
electrum_dash/gui/kivy/uix/screens.py
electrum_dash/gui/kivy/uix/ui_screens/receive.kv
electrum_dash/gui/qt/dark_dash_style.py
electrum_dash/gui/qt/dash_style.py
electrum_dash/gui/qt/main_window.py
electrum_dash/json_db.py

- do not run mixing on watching-only wallets with error msg
- qt/kivy block receving GUI when mixing with info msg about cause of block
- fix add_ps_tx (convert tx_type from IntEnum to int before placing to bd to not differ with from file loaded state)

PS block receving gui when mixing

---

RELEASE-NOTES
electrum_dash/coinchooser.py
electrum_dash/dash_ps.py
electrum_dash/gui/kivy/main_window.py
electrum_dash/gui/kivy/uix/dialogs/coins_dialog.py
electrum_dash/gui/kivy/uix/dialogs/privatesend.py
electrum_dash/gui/kivy/uix/screens.py
electrum_dash/gui/qt/main_window.py
electrum_dash/gui/qt/privatesend_dialog.py
electrum_dash/gui/qt/utxo_list.py
electrum_dash/tests/test_dash_ps.py
electrum_dash/version.py
electrum_dash/wallet.py

- modify check/add/rm for new denoms/collateral (allow collateral val 10000-100000 in some cases)
- modify _check_pay_collateral_tx_err (allow collateral val 10000-100000)
- psman: modify new denoms/collateral wfl behaviour (allow creating collateral, denoms from gui from singl other ps coin or from single denom withot change, create new denoms from minimal denoms without change with val 90000 if no funds in regular balance left)
p.s.:
- limit fee_overhead to minimal denom in PS coinchooser
- add allow_others option, test, qt/kivy gui

PrivateSend allow create small denoms from big one

---

RELEASE-NOTES
electrum_dash/commands.py
electrum_dash/dash_tx.py
electrum_dash/gui/qt/dash_qt.py
electrum_dash/gui/qt/protx_qt.py
electrum_dash/gui/qt/protx_wizards.py
electrum_dash/network.py
electrum_dash/protx.py
electrum_dash/tests/test_dash_tx.py
electrum_dash/tests/test_protx.py
electrum_dash/wallet.py

- qt:protx_wizard: exclude frozen coins/addrs
- qt:protx_wizard: support creating collateral with ProRegTx
- qt:protx_wizard: fix ExportToFileWizardPage
- qt:protx_wizard: limit Owner/Voting addresses to P2PKH
- dash_tx: add null outpoint to TxOutPoint, tests
- network: add new dash error messages
- protx/dash_tx/qt ui: support sending ProRegTx with null outpoint
- commands.py: remove legacy masternodes commands

Extend ProRegTx usage (allow creation of collateral in ProRegTx)

---

electrum_dash/gui/qt/protx_qt.py
electrum_dash/gui/qt/protx_wizards.py

Fix https://github.com/akhavr/electrum-dash/pull/119 changes, add lost breaks in payto address selection.

qt protx: fix payto address selection

---

RELEASE-NOTES
electrum_dash/commands.py
electrum_dash/dash_ps.py
electrum_dash/gui/qt/address_list.py
electrum_dash/gui/qt/main_window.py
electrum_dash/gui/qt/password_dialog.py
electrum_dash/gui/qt/privatesend_dialog.py
electrum_dash/gui/qt/seed_dialog.py
electrum_dash/keystore.py
electrum_dash/plugins/trezor/qt.py
electrum_dash/stacktraces.py
electrum_dash/tests/test_dash_ps.py
electrum_dash/version.py
electrum_dash/wallet.py

- limit dnspython version in contrib/requirements/requirements.txt (on 2.0.0 tests fail)
- fix PS_BIP32_KeyStore
- wallet: fix get_change_addresses_for_new_transaction (if change address is passed as parameter, test if it from ps_keystore)
- remove unused more denominate wfl denom_rounds from log (keep in wfl)
- privatesend: add support to hardware wallets
- remove staled code

PrivateSend: add support to mix on hw wallets (using ps_keystore)

---

electrum_dash/exchange_rate.py
electrum_dash/gui/qt/network_dialog.py
electrum_dash/network.py

- allow bypass Tor proxy for Fiat rates/history loading
- add Network/Proxy tab checkbox "Bypass Tor proxy for Fiat rates loading" (default off)

qt/exchange_rate add bypass Tor for Fiat option

---

electrum_dash/gui/kivy/main_window.py
electrum_dash/gui/kivy/uix/ui_screens/network.kv
electrum_dash/gui/qt/network_dialog.py
electrum_dash/network.py

- kivy: add fiat bypass tor option to electrum network popup

kivy: add fiat bypass tor to electrum net settings

---

electrum_dash/dash_ps.py
electrum_dash/gui/kivy/main_window.py
electrum_dash/gui/qt/main_window.py
electrum_dash/tests/test_dash_ps.py

- fix _calc_total_need_val to not modify `outupts_amounts` input param, instead return possilby modified value
- modify keyparis caching for small funds available (need to cache more keys to support multiple new denoms txs, max 5 for now)
- fix caching if zero funds available
- do not try create new denoms/collateral workflows if no funds available
- add _check_not_enough_funds to reset `not_enough_funds` condition on periodical intervals, not only when wallet updated
- when keypairs in state NeedCache/Caching is_waiting is False now

PS: fix keypairs calc on small/zero funds

---

electrum_dash/dash_ps.py
electrum_dash/gui/kivy/uix/dialogs/password_dialog.py
electrum_dash/gui/qt/address_list.py
electrum_dash/gui/qt/history_list.py
electrum_dash/gui/qt/main_window.py
electrum_dash/gui/qt/privatesend_dialog.py
electrum_dash/gui/qt/protx_wizards.py
electrum_dash/gui/qt/util.py
electrum_dash/gui/qt/utxo_list.py
electrum_dash/plugins/keepkey/keepkey.py
electrum_dash/plugins/safe_t/safe_t.py
electrum_dash/plugins/trezor/trezor.py
electrum_dash/tests/test_dash_ps.py
electrum_dash/transaction.py
electrum_dash/version.py
electrum_dash/wallet.py

- kivy: unfocus passwd field in passwd dlg on_dismiss (to fix back button behaviour)
- fix typo in qt/protx_wizards.py
- qt: fix GetDataThread finishing/waiting
- ps keystore: real derivation for get_address_path_str
- fix dash_ps POOL_MIN/MAX_PARTICIPANTS
- psman: remove _is_mine_lookahead
- psman: add can_find_untracked (to do find untracked when wallet is fully synced)
- psman: additional check for mine in/outs on denominate tx
- fixes for PS on HW wallets
- assorted fixes related to PS
- version to 4.0.4.0rc6

Post 4.x PrivateSend fixes

---

contrib/dash/travis/travis-build-osx.sh
electrum_dash/version.py

- Downgrade PyQt5 version to fix macOS Big Sur problems
- version to 4.0.4.1

Big sur fix qt version

---

electrum_dash/dash_tx.py
electrum_dash/gui/qt/dash_qt.py
electrum_dash/gui/qt/main_window.py
electrum_dash/gui/qt/protx_wizards.py
electrum_dash/network.py

* DashProRegTx.update_with_tx_data: update index only if output found
* ExtraPayloadWidget.get_extra_data: return copy of extra payload
instance
* Network.sanitize_tx_broadcast_response: find max len suitable msg
* qt: clear extra payload before reset_privatesend (available amount will be recalculated without extra payload)

various dip3 fixes (post 4.0.9.1)

---

electrum_dash/gui/qt/privatesend_dialog.py

- qt: fix protected_with_parent decorator (fix for passwordless standard/bip32 wallet)

qt: fix protected_with_parent decorator

---

.github/workflows/build_release.yml
.github/workflows/notify_slack.yml
.github/workflows/run_tests.yml

Fix notifications for cases where in PRs `secrets.SLACK_WEBHOOK_URL` is not available.

GitHub Actions: modify slack notify action to work with PRs

---

electrum_dash/gui/kivy/main_window.py
electrum_dash/gui/kivy/uix/dialogs/tx_dialog.py
electrum_dash/gui/kivy/uix/screens.py
electrum_dash/gui/qt/main_window.py
electrum_dash/gui/qt/transaction_dialog.py
electrum_dash/paymentrequest.py

- make_unsigned_request: set network for testnet (fix testnet `PayServer` usage)
- qt: fix sending Payment msg on tx broadcast
- kivy: fix sending Payment msg on tx broadcast
- add PaymentRequest.need_broadcast_tx property
- qt: check if tx need broadcast on PaymentRequest pay (related #174)
- kivy: check if tx need broadcast on PaymentRequest pay (related #174)

GUI: fix send Payment msg from qt/kivy gui

---

RELEASE-NOTES
electrum_dash/address_synchronizer.py
electrum_dash/coinchooser.py
electrum_dash/dash_msg.py
electrum_dash/dash_ps.py
electrum_dash/dash_tx.py
electrum_dash/gui/kivy/uix/dialogs/coins_dialog.py
electrum_dash/gui/kivy/uix/dialogs/privatesend.py
electrum_dash/gui/qt/main_window.py
electrum_dash/gui/qt/privatesend_dialog.py
electrum_dash/gui/qt/utxo_list.py
electrum_dash/tests/test_dash_ps.py
electrum_dash/version.py
electrum_dash/wallet.py
electrum_dash/wallet_db.py

- removed deprecatd `DSPoolState.SUCCESS`, added new `DSMessageIDs.ERR_SIZE_MISMATCH`
- Added GUI option "Group origin coins by address" disabled by default.
- New denom/collateral workflows use coins from one address by one tx, when option is enabled.
- When option is enabled add random delay betwen new denom/collateral workflows (30-300 sec).
related to #142

PS: option to group mix origin coins by address

---

electrum_dash/base_wizard.py
electrum_dash/gui/kivy/uix/dialogs/installwizard.py
electrum_dash/gui/kivy/uix/dialogs/seed_options.py

Related to #201
- fix #4326 (upstream 77e0d3745)
- wizard: call on_restore_seed, on_restore_bip39 through self.run. fixes #6895 (upstream b2ab2a9f6)
- kivy wizard: checkum bip39 seeds, because the virtual keyboard imposes the English wordlist (upstream 07b08738a)
- kivy: fix confirm_seed_dialog (broken in 77e0d3745e990e97ddbac5550e399f3e695af788) (upstream 620a6aaf9)
- kivy wizard: verify seed extension (upstream 940654145)

Some Kivy post 4.0.9 fixes from upstream

---

RELEASE-NOTES
electrum_dash/gui/kivy/main_window.py
electrum_dash/gui/kivy/uix/dialogs/tx_dialog.py
electrum_dash/gui/qt/transaction_dialog.py
electrum_dash/version.py

- kivy: add app.scan_qr_non_android (to simplify debugging on non android platform)
- kivy: rm TxDialog.update tx_type detect (unneeded)
- qt/kivy: do not get PS tx_type on incomplete txs (no txid for incomplete txs)
- qt: fix BaseTxDialog.update tx_type handling
must fix #195

kivy/qt: fix tx_type handling

---

electrum_dash/gui/qt/history_list.py

- qt: fix do_export_history (item key value -> bc_value) after key name chaned
Fix #211

qt: fix do_export_history (item key value -> bc_value)

---

electrum-dash
electrum_dash/base_wizard.py
electrum_dash/daemon.py
electrum_dash/gui/kivy/main_window.py
electrum_dash/gui/kivy/uix/dialogs/installwizard.py
electrum_dash/gui/kivy/uix/dialogs/password_dialog.py
electrum_dash/gui/qt/__init__.py
electrum_dash/gui/qt/installwizard.py
electrum_dash/gui/stdio.py
electrum_dash/gui/text.py
electrum_dash/tests/test_base_wizard.py
electrum_dash/tests/test_wallet_db.py
electrum_dash/wallet_db.py

- Add support to save uncompleted multisig wallets and then
continue setup when cosigners xpub is available.
Related to #192
Some screens:
1. "Save and exit" button is added when saving is possible:
<image src="https://user-images.githubusercontent.com/992125/111175340-008edb80-85b1-11eb-83a2-afaeed43bd27.png" width="250"> <image src="https://user-images.githubusercontent.com/992125/111175216-d9d0a500-85b0-11eb-93a6-870b2bf1bdc2.png" width="350">
2. Continue multisig setup, when already stored xpubs can be viewed (QR can be shown):
<image src="https://user-images.githubusercontent.com/992125/111176064-ad695880-85b1-11eb-82bc-e080d3f5bfdc.png" width="250"> <image src="https://user-images.githubusercontent.com/992125/111176067-ae01ef00-85b1-11eb-803e-addf7562d913.png" width="350">

add support to save uncompleted multisig wallets

---

electrum_dash/base_wizard.py
electrum_dash/gui/kivy/uix/dialogs/installwizard.py
electrum_dash/gui/qt/installwizard.py

- Installwizard: show hw xpub after adding cosigner
It could be useful, for example, when setting up 2of2 on desktop and mobile.
Related to #194
Must be rebased with conflicts fixed after merge of #219

installwizard: show hw xpub after adding cosigner

---

electrum_dash/commands.py
electrum_dash/daemon.py

Add `--set_current` command option for `load_wallet` command,
which allow to run commands where wallet required without additional `wallet_path` option.
Fix: #226

commands load_wallet: add set current for commands option

---

electrum_dash/gui/kivy/uix/dialogs/settings.py
electrum_dash/gui/kivy/uix/ui_screens/history.kv
electrum_dash/wallet.py

- kivy: add show tx type to settings
- kivy history.kv: show tx type
- wallet.get_full_history: set empty str tx type when show_dip2 disabled (get_full_history should return with str in tx_type)
Fix #206

Fix kivy: show tx type again

---

electrum_dash/gui/kivy/uix/dialogs/confirm_tx_dialog.py
electrum_dash/wallet.py

- wallet/kivy: fix feerate calc (float Decimal conversion)
Fix #257

wallet/kivy: fix feerate calc (float Decimal conversion)

---

electrum_dash/gui/kivy/uix/dialogs/tx_dialog.py
electrum_dash/gui/qt/confirm_tx_dialog.py
electrum_dash/gui/qt/main_window.py
electrum_dash/gui/qt/privatesend_dialog.py
electrum_dash/gui/qt/transaction_dialog.py
electrum_dash/gui/qt/util.py

BlockingWaitingDialog work unstable on older versions of Qt5.
Replace it with WaitingDialog plus corresponding code change.
Some other qt fixes.
- qt: fix pay_onchain_dialog
- qt: fix qrcoin icon in transaction_dialog.py
- qt: fix transaction_dialog.py update_fee_fields
- qt/kivy: rm unused _add_info_to_tx_from_wallet_and_network (RBF)
- qt: use WaitingDialog instead BlockingWaitingDialog

Qt fix: remove BlockingWaitingDialog use, other qt fixes

---

electrum_dash/dash_ps.py
electrum_dash/ecc.py
electrum_dash/interface.py
electrum_dash/util.py

Follow up to #266
- dash_ps: enhance logging of dsq message timeout (Will write about no peers to mix instead `TimeoutError`)
- remove legacy code, add whitespace in ecc.py

Enhance PS gui logging about session timeouts

---

RELEASE-NOTES
electrum_dash/gui/kivy/main_window.py
electrum_dash/gui/kivy/uix/dialogs/privatesend.py
electrum_dash/gui/kivy/uix/dialogs/question.py

- kivy: ElectrumWindow.protected add on_failure, fix start_mixing
- kivy: Question: run callback in on_dismiss with default False arg
Fix #274

Kivy: fix start mixing with protected method

---

electrum_dash/address_synchronizer.py
electrum_dash/gui/qt/address_list.py
electrum_dash/gui/qt/network_dialog.py
electrum_dash/tests/test_wallet_vertical.py

- address_synchronizer: add _addrs_with_coins_cache
- add _tx_deltas_cache
- add test_tx_deltas_cache, test_addrs_with_coins_cache
- qt/address_list: optimize get_addresses
- qt/address_list: by default filter out PS keystore
- qt/network_dialog.py: set minimum width to 700

Optimize for big PS wallets (wallet/qt address list)

---

electrum_dash/gui/kivy/main.kv
electrum_dash/gui/kivy/uix/dialogs/addresses.py
electrum_dash/gui/kivy/uix/ui_screens/status.kv

Two small fixes on Kivy GUI:
In `uix/ui_screens/status.kv`, when touched seed and then cancel Pin/Question
popup, second try to show seed is not working. Same for privk in `uix/dialogs/addresses.py`.
This commit fixes this problem:
- kivy: fix RefLabel on_touched processing
Second problem can be reproduced only in Kivy+Linux. If `status.kv` popup is shown
and window is closed by window manager means, exception is raised (parent is set to None,
but `app.wallet` is unloaded already). Possibly it should be fixed by:
- kivy status.kv: update balance only when shown

Fix kivy RefLabel on_touched; status.kv: update balances only when shown

---

electrum_dash/gui/qt/privatesend_dialog.py

- fix qt/privatesend_dialog: add config to init calls (`SeedLayout`, `ShowQRTextEdit`, changed in upstream code)

fix qt/privatesend_dialog: add config to init calls

---

electrum_dash/plugins/trezor/clientbase.py
electrum_dash/plugins/trezor/qt.py

- trezor plugin: allow skip session clear on wallet close
Add requested option for trezor plugin.
Fix #291
<image src="https://user-images.githubusercontent.com/992125/131226109-9d257af5-1473-4ea0-9a01-b7267b959d9e.png" width="450">

trezor plugin: allow skip session clear on wallet close

---

electrum_dash/storage.py
electrum_dash/tests/test_storage.py

- storage: more write attempts, add test_storage.py
Changes for Win, where antivirus software can block wallet files randomly.
Fix #290

storage: more write attempts, add test_storage.py

---

electrum_dash/gui/kivy/uix/screens.py
electrum_dash/gui/kivy/uix/ui_screens/history.kv

- kivy: add "Quick Scan", "Quick Receive" to main screen

Kivy: add "Quick Scan", "Quick Receive" to main screen

---

electrum_dash/gui/kivy/uix/dialogs/privatesend.py

- kivy: fix PrivateSend mixing progress refresh

Kivy: fix PrivateSend mixing progress refresh

---

electrum_dash/gui/kivy/uix/dialogs/password_dialog.py

Fix #313 for cases when new wallet is created.
- fix: kivy: allow switch to digits only password dialog

fix: Kivy: allow switch to digits only password dialog

---

electrum_dash/gui/kivy/uix/dialogs/password_dialog.py

Fix #313 (second) for cases when new wallet is created.
- fix2: Kivy: allow switch to digits only password dialog

fix2: Kivy: allow switch to digits only password dialog

---

electrum_dash/gui/qt/main_window.py

- qt: add warning on possible lags on HW devices
Fix #306
Fix #304
If option "Don't show this again." is enabled,
then enabling warning back is possible via command line:
```
electrum-dash -o setconfig "hw_no_lags_warn" false
```

Qt: add warning on possible lags on HW devices

---

electrum_dash/gui/kivy/main_window.py
electrum_dash/gui/kivy/uix/dialogs/dash_kivy.py
electrum_dash/gui/kivy/uix/screens.py

- kivy: use popups for tx sending/error messages
Use more robust Popup messages for info on transaction
sending outcome.

Kivy: use popups for Tx sending/error messages

---

electrum_dash/gui/kivy/main_window.py
electrum_dash/gui/kivy/uix/dialogs/dash_kivy.py
electrum_dash/gui/kivy/uix/ui_screens/network.kv
electrum_dash/gui/qt/network_dialog.py
electrum_dash/network.py

- network: allow blacklist electrum servers
Related #323
Added:
- Detect electrum network servers with `tx-txlock-conflict` and blacklist automatically.
- No timeout for removing from blacklist.
- add Qt/Kivy UI to manually `Blacklist`/`Unblacklist` servers.
Qt interface (with right mouse button on items):
Kivy interface (top menu show servers popup now):

Network: allow blacklist electrum servers

---

electrum_dash/gui/qt/main_window.py
electrum_dash/gui/qt/settings_dialog.py

- Qt: add option to save local transaction before send (off by default)

Qt: add option to save local transaction before send
